#!/bin/bash
curl -s -H 'User-Agent: Mozilla/5.0' -H 'Referer: https://www.anzcofoods.com/' "https://www.anzcofoods.com/assets/Uploads/ANZCO-Foods-Beef-Logo-V2__FocusFillWyIwLjAwIiwiMC4wMCIsNjEwLDYxMF0_ExtRewriteWyJqcGciLCJ3ZWJwIl0.webp" -o public/brands/anzco-beef.webp
curl -s -H 'User-Agent: Mozilla/5.0' -H 'Referer: https://www.anzcofoods.com/' "https://www.anzcofoods.com/assets/Uploads/Greenstone-Creek-by-ANZCO-Foods-Logo__FocusFillWyIwLjAwIiwiMC4wMCIsNjEwLDYxMF0_ExtRewriteWyJqcGciLCJ3ZWJwIl0.webp" -o public/brands/greenstone-creek.webp
curl -s -H 'User-Agent: Mozilla/5.0' -H 'Referer: https://www.anzcofoods.com/' "https://www.anzcofoods.com/assets/Uploads/Stony-River-Black-Angus-by-ANZCO-Foods-Logo__FocusFillWyIwLjAwIiwiMC4wMCIsNjEwLDYxMF0_ExtRewriteWyJqcGciLCJ3ZWJwIl0.webp" -o public/brands/stony-river.webp
curl -s -H 'User-Agent: Mozilla/5.0' -H 'Referer: https://www.anzcofoods.com/' "https://www.anzcofoods.com/assets/Uploads/Ocean-Beef-by-ANZCO-Foods-Logo__FocusFillWyIwLjAwIiwiMC4wMCIsNjEwLDYxMF0_ExtRewriteWyJqcGciLCJ3ZWJwIl0.webp" -o public/brands/ocean-beef.webp
curl -s -H 'User-Agent: Mozilla/5.0' -H 'Referer: https://www.anzcofoods.com/' "https://www.anzcofoods.com/assets/Uploads/ANZCO-Foods-Lamb-Logo__FocusFillWyIwLjAwIiwiMC4wMCIsNjEwLDYxMF0_ExtRewriteWyJqcGciLCJ3ZWJwIl0.webp" -o public/brands/anzco-lamb.webp
curl -s -H 'User-Agent: Mozilla/5.0' -H 'Referer: https://www.anzcofoods.com/' "https://www.anzcofoods.com/assets/Uploads/Maimoa-Lamb-by-ANZCO-Foods-Logo__FocusFillWyIwLjAwIiwiMC4wMCIsNjEwLDYxMF0_ExtRewriteWyJqcGciLCJ3ZWJwIl0.webp" -o public/brands/maimoa-lamb.webp
curl -s -H 'User-Agent: Mozilla/5.0' -H 'Referer: https://www.anzcofoods.com/' "https://www.anzcofoods.com/assets/Uploads/Angel-Bay-by-ANZCO-Foods-Logo__FocusFillWyIwLjAwIiwiMC4wMCIsNjEwLDYxMF0_ExtRewriteWyJqcGciLCJ3ZWJwIl0.webp" -o public/brands/angel-bay.webp
curl -s -H 'User-Agent: Mozilla/5.0' -H 'Referer: https://www.anzcofoods.com/' "https://www.anzcofoods.com/assets/Uploads/ANZCO-Foods-100-Beef-Burger-Patties__FocusFillWyIwLjAwIiwiMC4wMCIsNjEwLDYxMF0_ExtRewriteWyJqcGciLCJ3ZWJwIl0.webp" -o public/brands/burger-patties.webp
